# Site settings
title: 说点什么呢...
email: bizhichaoabc@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

permalink: 'pretty'

timezone: '+0800'

paginate: 10

gems:
  - jekyll-archives

jekyll-archives:
  enabled: all
