# Site settings
title: 说点什么呢...
email: bizhichaoabc@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  这是在学习jekyll中建立的测试blog
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  zcbi

# Build settings
markdown: kramdown

permalink: 'pretty'

timezone: '+0800'

paginate: 10

# gems:
# - jekyll-archives

jekyll-archives:
enabled: all
